# Generated by Django 6.0 on 2025-12-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='_aadhaar_number',
            field=models.TextField(blank=True, db_column='aadhaar_number', null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='aadhaar_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pan_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pan_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pan_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
