# Generated by Django 5.1.4 on 2025-12-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sellerprofile__aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
