# Generated by Django 6.0 on 2025-12-17 06:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_estimated_delivery_order_tracking_updates_and_more'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='orders.order'),
        ),
        migrations.AddField(
            model_name='payout',
            name='razorpay_payout_id',
            field=models.CharField(blank=True, help_text='Razorpay Payout ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='utr_number',
            field=models.CharField(blank=True, help_text='UTR/Transaction Reference', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='payout',
            name='bank_details_snapshot',
            field=models.TextField(blank=True, help_text='Bank Account/UPI used for this request'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['seller', 'status'], name='sellers_pay_seller__676e49_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['order'], name='sellers_pay_order_i_391da4_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['-created_at'], name='sellers_pay_created_bd2402_idx'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['APPROVED', 'PROCESSING', 'PAID'])), fields=('seller', 'order'), name='unique_active_payout_per_order'),
        ),
    ]
