# Generated by Django 6.0 on 2025-12-10 13:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('RETURN', 'Return (Refund)'), ('EXCHANGE', 'Exchange (Replace)')], default='RETURN', max_length=20)),
                ('reason', models.CharField(choices=[('DEFECTIVE', 'Defective/Damaged'), ('WRONG_ITEM', 'Wrong Item Received'), ('NOT_AS_DESCRIBED', 'Not as Described'), ('SIZE_ISSUE', 'Size/Fit Issue'), ('QUALITY_ISSUE', 'Quality Issue'), ('CHANGED_MIND', 'Changed Mind'), ('BETTER_PRICE', 'Found Better Price'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Detailed explanation')),
                ('images', models.JSONField(default=list, help_text='URLs of uploaded images')),
                ('video_url', models.URLField(blank=True, help_text='Video evidence URL', null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received by Seller'), ('INSPECTED', 'Inspected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('seller_response', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('inspection_result', models.CharField(choices=[('PENDING', 'Pending Inspection'), ('APPROVED', 'Approved - Product OK'), ('REJECTED', 'Rejected - Product Damaged by Customer'), ('PARTIAL', 'Partial - Missing Items')], default='PENDING', max_length=20)),
                ('inspection_notes', models.TextField(blank=True)),
                ('inspection_images', models.JSONField(default=list)),
                ('return_tracking_number', models.CharField(blank=True, max_length=100)),
                ('pickup_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_processed_at', models.DateTimeField(blank=True, null=True)),
                ('exchange_tracking_number', models.CharField(blank=True, max_length=100)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for suspicious activity')),
                ('fraud_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
                ('exchange_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(choices=[('DEFECTIVE', 'Defective/Damaged'), ('WRONG_ITEM', 'Wrong Item Received'), ('NOT_AS_DESCRIBED', 'Not as Described'), ('SIZE_ISSUE', 'Size/Fit Issue'), ('QUALITY_ISSUE', 'Quality Issue'), ('CHANGED_MIND', 'Changed Mind'), ('BETTER_PRICE', 'Found Better Price'), ('OTHER', 'Other')], max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['customer', 'status'], name='returns_ret_custome_76a571_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['seller', 'status'], name='returns_ret_seller__da6bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order'], name='returns_ret_order_i_30fb33_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['-created_at'], name='returns_ret_created_d2df9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='returnitem',
            unique_together={('return_request', 'order_item')},
        ),
    ]
