# Generated by Django 6.0 on 2025-12-17 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0002_product_brand_product_deleted_at_and_more'),
        ('coupons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='cart_cart_user_id_b645f9_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_id'], name='cart_cart_session_f55f25_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='cart_cartit_cart_id_4bd8c3_idx'),
        ),
    ]
